# Generated by Django 4.2.16 on 2024-09-11 07:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LoginTable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.CharField(choices=[('doctor', 'doctor'), ('staff', 'staff'), ('patient', 'patient')], default='patient', max_length=200)),
                ('email', models.EmailField(max_length=200, unique=True)),
                ('password', models.CharField(max_length=200)),
                ('password1', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Specialization',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sname', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='StaffRegistration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=200)),
                ('last_name', models.CharField(max_length=200)),
                ('staff_id', models.IntegerField(unique=True)),
                ('mobile_no', models.IntegerField(unique=True)),
                ('type', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='account_app.logintable')),
            ],
        ),
        migrations.CreateModel(
            name='PatientRegistration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=200)),
                ('last_name', models.CharField(max_length=200)),
                ('gender', models.CharField(max_length=100)),
                ('mobile_no', models.IntegerField(unique=True)),
                ('address', models.TextField()),
                ('type', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='account_app.logintable')),
            ],
        ),
        migrations.CreateModel(
            name='DoctorRegistration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=200)),
                ('last_name', models.CharField(max_length=200)),
                ('fee', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('mobile_no', models.IntegerField(unique=True)),
                ('specialization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='account_app.specialization')),
                ('type', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='account_app.logintable')),
            ],
        ),
    ]
