# Generated by Django 4.2.16 on 2024-09-11 09:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='logintable',
            name='user',
            field=models.CharField(choices=[('patient', 'patient'), ('staff', 'staff'), ('doctor', 'doctor')], default='patient', max_length=200),
        ),
    ]
