# Generated by Django 4.2.16 on 2024-09-12 12:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account_app', '0004_alter_logintable_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='logintable',
            name='user',
            field=models.CharField(choices=[('staff', 'staff'), ('patient', 'patient'), ('doctor', 'doctor')], default='patient', max_length=200),
        ),
    ]
