# Generated by Django 4.2.16 on 2024-09-20 15:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account_app', '0006_alter_logintable_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='status',
            field=models.CharField(choices=[(0, 0), ('Approved', 'Approved'), ('Canceled', 'Canceled')], default=0, max_length=200),
        ),
        migrations.AlterField(
            model_name='logintable',
            name='user',
            field=models.CharField(choices=[('staff', 'staff'), ('patient', 'patient'), ('doctor', 'doctor')], default='patient', max_length=200),
        ),
        migrations.CreateModel(
            name='Prescription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('medicine', models.CharField(max_length=200)),
                ('dosage', models.CharField(max_length=200)),
                ('instructions', models.TextField()),
                ('appointment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='account_app.appointment')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='account_app.patientregistration')),
            ],
        ),
    ]
