# Generated by Django 4.2.16 on 2024-09-22 06:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account_app', '0008_bill'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bill',
            name='total_amount',
        ),
        migrations.AlterField(
            model_name='logintable',
            name='user',
            field=models.CharField(choices=[('staff', 'staff'), ('doctor', 'doctor'), ('patient', 'patient')], default='patient', max_length=200),
        ),
    ]
